// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHs5i28mPAwOk1UCgvJ77ont2LvWGkjuE',
    appId: '1:330343621662:android:2d9ca5a485f8ebefdd3a0f',
    messagingSenderId: '330343621662',
    projectId: 'sushi-wroclaw-69',
    storageBucket: 'sushi-wroclaw-69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnpTYL_JiG3mZgxMISO9-2dDxuQu2DBxM',
    appId: '1:330343621662:ios:4e122a64acdc63d1dd3a0f',
    messagingSenderId: '330343621662',
    projectId: 'sushi-wroclaw-69',
    storageBucket: 'sushi-wroclaw-69.appspot.com',
    iosClientId: '330343621662-fr8uc8tkk7vh8h5tlst3pf2na293eap8.apps.googleusercontent.com',
    iosBundleId: 'com.adaigosia.najlepszeSushiWroclaw',
  );
}
